version: '3.8'

services:
    backend:
        restart: unless-stopped
        build: ./backend
        container_name: django_ddr
        volumes:
            
        entrypoint: /app/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/app/django_static
        ports:
          - "8000:8000"
    frontend:
        restart: unless-stopped
        container_name: react_ddr
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - 3000:3000
        volumes:
            - static_volume:/app/frontend/server/django_static
        depends_on:
            - backend
    nginx:
        image: nginx:1.19.6
        ports:
            - 80:80
        volumes:
            - ./nginx/development:/etc/nginx/conf.d
        depends_on:
            - frontend

volumes:
    static_volume: {}
